### ISSUE TITLE
Prevent the Node from Allowing the Battery to Fall Below 10%

### ISSUE THREAD

**Issue by orbitllc** [chipmc/SeeInsights-LoRA-Node#17]

**Comment by chipmc** [comment]
@orbitllc , please help me test this by using a device with a low battery - Device should just sleep when the battery is below 10% charge.  Also please capture log when the battery drains as I am testing a more reliable way to catch this condition using voltage and the battery alert interrupt.

**Comment by chipmc** [comment]
@orbitllc sorry, please see my latest commit on this branch 11.6

**Comment by chipmc** [comment]
I believe we have addressed this issue.
